### ISSUE TITLE
rnxdownload:: get metrica obs

### ISSUE THREAD

**Issue by demanasta** [DSOlab/autobern#12]
- Data is RINEX 3 format but name is RINEX 2 short_name!!

- path for ftp data...
  ... /\_OFF_STA_NAME_/\_YYYY_/\_MMMM_/\_DOM_/

> \_OFF_STA_NAME_  : name in UPPER case letter
>\_MMMM_ /\_DOM_ : month and day of month maybe missing from rnxdownload

- data compressed on .zip format !! 
- no hatanaka format

**Comment by xanthospap** [comment]
Working on this ....
rnxdwnl_impl.py: Special possible RINEX names are added if 'dc_name': 'DSO_MTRC' to handle this data.
!!ALWAYS!! use 'dc_name': 'DSO_MTRC' for these stations in the database

**Comment by xanthospap** [comment]
Μητς, η βάση λέει ότι αυτά τα RINEX είναι version 2. Κάνε τα version 3.
Αν η βάση πει ότι το dc είναι 'dc_name': 'DSO_MTRC', τότε θα ψάχνει (και) για 
ονόματα σαν αυτά της metrica -- και μόνο τότε--

**Comment by xanthospap** [comment]
path for ftp data...
... /_OFF_STA_NAME_/_YYYY_/_MMMM_/_DOM_/

Αυτό στη βάση πρέπει να γράφεται:
... /_OFF_STA_NAME_/_YYYY_/_MM_/_DD_/
Γενικά, οι ημ/νίες ακολουθούν τη μορφή:
['_YYYY_', '_DDD_', '_MM_', '_DD_', '_YY_']

**Comment by xanthospap** [comment]
Παρόλα αυτά, έχουμε το εξής πρόβλημα· στο
... /OFF_STA_NAME/YYYY/MM/DD/
το 'OFF_STA_NAME' είναι uppercase (π.χ. ITEA/03/01/itea....zip) ενώ σε άλλα repository (π.χ. crl) είναι με μικρά!
Κάπως πρέπει να διακρίνονται.
