### ISSUE TITLE
Missing domes numbers

### ISSUE THREAD

**Issue by xanthospap** [DSOlab/autobern#7]
ktch 12659M001
DIOP 12602M007
ARK2 12644M002 (note arki is 12644M001)
LEPE 12660M001
MILO 12758M001

**Comment by demanasta** [comment]
done except MILO 12758M001
is this NOA or NTUA station???

**Comment by xanthospap** [comment]
έλα ντε .......

**Comment by demanasta** [comment]
ρε το milo είναι σε άλλη χώρα!
https://www.epncb.oma.be/_networkdata/logfile.php?name=milo00ita_20041125.log_old

**Comment by xanthospap** [comment]
Ντάξει, Σικελία είνα σχεδόν ελλάδα .....
Αν το έχουμε στη βάση σβήστο Μητς
