### ISSUE TITLE
double record on CRD file (e.g. PYLO)

### ISSUE THREAD

**Issue by demanasta** [DSOlab/autobern#9]
on [make_apriori_crd.py](https://github.com/DSOlab/autobern/blob/main/bin/make_apriori_crd.py) line 121
`sta_list = [s['mark_name_OFF'].upper() for s in netsta_dct]` 
a list created using mark_name_OFF but the unique 4-char name of each station is mark_name_DSO

This is the conflict!

**Comment by xanthospap** [comment]
Ναι ρε Μήτς, πολύ σωστός.

Fixed, committed and pushed bugfix
